title: Corissa Goodrich
logo: /assets/img/logo.png
description: M.S. Data Science DePaul University. 

Leveraging expertise in data science & artificial intelligence for actionable healthcare insight.

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
