title: Corissa Goodrich
logo: /assets/img/logo.png
description: M.S. Data Science DePaul University. Dedicated to leveraging expertise in data science & artificial intelligence for actionable insights in health & wellbeing.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
